aws/aws-crt-kotlin

gradle.properties
(none)
Presetting version number for future release.
=> Pre 0.4.1 release

gradle.properties
*Issue #, if available:* N/A
* update kotlin, coroutine, and kotest versions to latest
=> Chore kotlin version bumps

gradle.properties
N/A
Set project-level version to 0.4.1-alpha in preparation for release.
=> chore: release 0.4.1-alpha

gradle.properties
=> chore: bump version to 0.4.2-SNAPSHOT

gradle.properties
Companion PRs:
* https://github.com/awslabs/smithy-kotlin/pull/506
* https://github.com/awslabs/aws-sdk-kotlin/pull/360
* Update Kotlin and Dokka to `1.5.31` to support documentation generation
=> Bump Kotlin version to latest release

gradle.properties
N/A
Prepare for `0.5.0-alpha` release
=> chore: release 0.5.0-alpha

gradle.properties
awslabs/aws-sdk-kotlin#434
Upgrade Kotlin from 1.5.31 to 1.6.10 (requires also upgrading coroutines and ktlint).
=> feat: upgrade to Kotlin 1.6.10

CHANGELOG.md, gradle.properties
=> chore: release 0.5.2

gradle.properties
(none)
Prepare for **0.5.3** release.
=> chore: prepare for 0.5.3 release

CHANGELOG.md, gradle.properties
(none)
Merge changelog and version bump from **release** branch.
=> chore: prepare for 0.5.4 release

CHANGELOG.md, gradle.properties
(none)
Post-release SNAPSHOT bump
=> chore: prepare for 0.5.5 release

build.gradle.kts, gradle.properties
=> chore: upgrade to Kotlin 1.7

.github/workflows/changelog-verification.yml
(none)
Enable changelog verification as a workflow, exactly the same as [smithy-kotlin#680](https://github.com/awslabs/smithy-kotlin/pull/680).
=> chore: enable verification of changelog entries for PRs

.github/workflows/changelog-verification.yml, CONTRIBUTING.md
=> chore: add changelog instructions and correct main branch reference in CONTRIBUTING

.changes/428e757e-6e6d-4c92-b6bd-600b2194771e.json, gradle.properties
(none)
Upgrade Kotlin version to 1.7.10.
=> Chore kotlin 1.7.10

.changes/b633d601-1926-47e6-9304-1c8b24a511d9.json, .editorconfig, build.gradle.kts, elasticurl/build.gradle.kts, gradle.properties, src/common/src/aws/sdk/kotlin/crt/Log.kt, src/common/src/aws/sdk/kotlin/crt/auth/signing/AwsSigningConfig.kt, src/common/src/aws/sdk/kotlin/crt/http/HttpHeaderBlock.kt, src/common/src/aws/sdk/kotlin/crt/http/HttpProxyOptions.kt, src/common/src/aws/sdk/kotlin/crt/io/SocketOptions.kt, src/common/src/aws/sdk/kotlin/crt/io/TlsVersion.kt
N/A
Upgrade Kotlin to 1.8.0 and other 3rd party dependencies to their latest versions.
=> chore: upgrade dependencies

.changes/532b5017-15ee-4c6d-9250-4e7b2ff978a3.json, gradle.properties, src/jvm/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerJVM.kt
N/A
Update Java CRT dependency to 0.21.7
=> misc: update Java CRT dependency to 0.21.7

.changes/b062a6cf-d42b-4104-a51d-48d9cc992a75.json, .changes/f4d68f74-f47e-4157-a78c-2847b4311f36.json, gradle.properties
N/A
* Update Kotlin to 1.8.22
* Update kotlinx.coroutines to 1.7.3
=> chore: update kotlin to 1.8.22; kotlinx.coroutines to 1.7.3

.changes/ffcbc974-9da9-463c-9813-798dc395baae.json, gradle.properties
=> chore: bump crt-java to latest

.changes/c370cdf8-3d1b-4ef0-a236-9ffab0901f6f.json, gradle.properties
=> misc: upgrade aws-crt-java version

.changes/9746125e-3a57-412f-9c1b-6912c3920601.json, build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> misc: upgrade dependencies

build.gradle.kts
=> misc: upgrade build plugin

build.gradle.kts
=> fix: bump build plugin to 0.2.8

.github/workflows/artifact-size-metrics.yml, build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
N/A
Added artifact size metrics plugin and misc changes to support the addition.
Note: The plugin currently runs because of the database being bootstrapped in my personal AWS account. 
=> feat: artifact size metrics

.github/workflows/artifact-size-metrics.yml, gradle/libs.versions.toml
N/A
Includes small fix to ASM workflow
=> misc: repo tools version bump

gradle/libs.versions.toml
N/A
This PR upgrades the repo tools version 
=> misc: version bump repo tools

.brazil.json
=> misc: prune transformation config

.changes/1df4ae4b-0bba-4e59-9933-47a7f6bb8bac.json, .changes/b92432b1-14e7-4aff-ad44-05ee02b0c416.json, gradle/libs.versions.toml
=> misc: upgrade to Kotlin 2.0.10

.changes/49b860c3-3fce-40fa-acf7-e97650f49016.json, gradle/libs.versions.toml
=> misc: Upgrade Kotlin version

.gitignore
(none)
Adds the Kotlin/Native **.kotlin/** directory to the Git ignore list.
=> chore: add .kotlin/ to .gitignore

CHANGELOG.md, aws-crt-kotlin/build.gradle.kts, build-support/src/main/kotlin/aws/sdk/kotlin/gradle/crt/CMakeUtils.kt, build-support/src/main/kotlin/aws/sdk/kotlin/gradle/crt/NativeUtils.kt, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
=> kn: merge from main, upgrade to latest aws-kotlin-repo-tools

gradle/libs.versions.toml
=> kn: upgrade to latest build plugin

gradle/wrapper/gradle-wrapper.properties
=> misc: gradle version bump

gradle/libs.versions.toml
=> misc: bump build plugin version

.github/workflows/merge-main.yml
N/A
Adds a workflow that attempts to merge main into feature branches every work day at midnight (PST)
=> feat: main to feature branches merge

aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/EventLoopGroupNative.kt, aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/TlsContextNative.kt
=> kn: initialize CRT in `TlsContext`

.github/workflows/artifact-size-metrics.yml
=> misc: use aws-kotlin-repo-tools show-results action

.github/workflows/ci.yaml, build-support/src/main/kotlin/aws/sdk/kotlin/gradle/crt/CMakeTasks.kt
=> kn: re-enable cross-compilation on Linux hosts

.changes/70d47326-b0a7-4d9c-bdc0-1bba1a7debe6.json, .github/workflows/changelog-verification.yml
=> misc: validate changelogs using `kat` tool

gradle/libs.versions.toml
=> misc: repo tools v0.4.34

gradle/libs.versions.toml
=> misc: repo tools v0.4.35

gradle/libs.versions.toml
=> misc: bump to latest version of aws-kotlin-repo-tools

gradle.properties
=> misc: bump to 0.11.4-SNAPSHOT

build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
N/A
Enables custom ktlint rules from repo tools
See: https://github.com/aws/aws-kotlin-repo-tools/pull/130
=> misc: enable custom ktlint rules

.github/workflows/api-compat-verification.yml, .github/workflows/ci.yaml, .github/workflows/closed-issue-message.yml, .github/workflows/jreleaser.yml, .github/workflows/lint.yml, .github/workflows/merge-main.yml, .github/workflows/stale_issue.yml
(none)
This change adds minimal permissions to our GitHub workflows.
=> chore: add missing permissions for GitHub workflows

gradle/libs.versions.toml
=> misc: bump aws-kotlin-repo-tools
