aws/aws-crt-kotlin

- elasticurl/src/commonMain/kotlin/Application.kt
- src/common/src/aws/sdk/kotlin/crt/io/Uri.kt
- src/common/test/aws/sdk/kotlin/crt/auth/signing/SigningTest.kt
- src/common/test/aws/sdk/kotlin/crt/http/HttpClientTest.kt
- src/common/test/aws/sdk/kotlin/crt/io/UriTest.kt
Addresses awslabs/aws-sdk-kotlin#310
Fixes scattered locations where URI ports are not respected (but hosts are). Also, adds convenience getters for URI properties **hostAndPort** and **authority**.
> fix: utilize endpoint ports

- .github/workflows/ci.yaml
- builder.json
N/A
* Add windows target to CI
* Adds macos target to CI
> chore: add mac and windows to ci

- build.gradle.kts
- gradle.properties
- src/common/src/aws/sdk/kotlin/crt/auth/signing/AwsSigner.kt
- src/common/src/aws/sdk/kotlin/crt/auth/signing/AwsSigningConfig.kt
- src/common/src/aws/sdk/kotlin/crt/auth/signing/AwsSigningResult.kt
- src/common/test/aws/sdk/kotlin/crt/auth/signing/SigningTest.kt
- src/jvm/src/aws/sdk/kotlin/crt/auth/signing/AwsSignerJVM.kt
N/A
* expose sigva algorithm and add `sign()` method that returns an `AwsSigningResult`
> feat: sigva

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
related: https://github.com/awslabs/aws-sdk-kotlin/issues/473
* Upgrade crt to 0.16.3 (which includes Mac M1 support)
* Upgrade kotlin to 1.6.21
* Upgrade gradle to 7.4.2
The last two should help build machine size/caches by aligning versions we use downstream.
> feat: upgrade kotlin 1.6.21; gradle 7.4.2

- .changes/02e5ad67-aad8-4802-86fd-475ed01480f8.json
- gradle.properties
- src/common/src/aws/sdk/kotlin/crt/io/TlsCipherPreference.kt
- src/jvm/src/aws/sdk/kotlin/crt/io/TlsContextJVM.kt
Closes #55 
Upgrades the **aws-crt-java** dependency to 0.19.0 to get the fix for the Mac dlopen issue.
**Companion PRs**: [smithy-kotlin#689](https://github.com/awslabs/smithy-kotlin/pull/689), [aws-sdk-kotlin#682](https://github.com/awslabs/aws-sdk-kotlin/pull/682)
> fix: upgrade aws-crt-java dependency to fix Mac dlopen issue

- .changes/3c9cedab-7cd3-479c-b887-0cbdceeb9341.json
- CONTRIBUTING.md
(none)
Update and clarify the contributing guidelines to more explicitly detail:
* Expected format for changelog entries
Similar to [smithy-kotlin#706](https://github.com/awslabs/smithy-kotlin/pull/706) except ~~without the commit guidelines because those don't exist in this guide~~ also add new commit guidelines.
> chore: update/clarify changelog instructions in CONTRIBUTING.md

- .changes/d56dbe9f-1d82-4c2d-963d-23e4a406f381.json
- gradle.properties
*Issue #, if available:* [aws-sdk-kotlin#715](https://github.com/awslabs/aws-sdk-kotlin/issues/715)
Temporarily works around [dokka#2679](https://github.com/Kotlin/dokka/issues/2679) by enabling non-hierarchical project compatibility mode
**Companion PRs**: [smithy-kotlin#711](https://github.com/awslabs/smithy-kotlin/pull/711) & [aws-sdk-kotlin#716](https://github.com/awslabs/aws-sdk-kotlin/pull/716)
> fix: enable intra-repo links in API ref docs

- .changes/1695ebf6-1351-4555-8ab9-d90c91622549.json
- src/common/src/aws/sdk/kotlin/crt/http/HttpStream.kt
- src/jvm/src/aws/sdk/kotlin/crt/http/HttpStreamJVM.kt
https://github.com/awslabs/smithy-kotlin/issues/759
This PR adds a `writeChunk` method to HttpStream. This wraps [Java CRT's writeChunk method](https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/http/HttpStream.java#L71), which is used to make chunked transfer-encoding requests using CRT's HTTP engine.
> feat: add `writeChunk` method to HttpStream

- src/common/src/aws/sdk/kotlin/crt/http/HttpClientConnection.kt
- src/jvm/src/aws/sdk/kotlin/crt/http/HttpClientConnectionJVM.kt
(none)
Adds an additional `id` field to the HTTP connection interface to improve traceability.
**Companion PR**: [smithy-kotlin#796](https://github.com/awslabs/smithy-kotlin/pull/796)
> feat: add additional fields for connection tracing

- api/android/aws-crt-kotlin.api
- api/jvm/aws-crt-kotlin.api
- build.gradle.kts
- builder.json
- gradle.properties
N/A
This adds the binary-compatibility-validator plugin which was previously added in [smithy-kotlin](https://github.com/awslabs/smithy-kotlin/pull/808) and [aws-sdk-kotlin](https://github.com/awslabs/aws-sdk-kotlin/pull/856).
Also this removes the `kotlin.mpp.enableGranularSourceSetsMetadata` property because it is now deprecated and prints a warning during builds: 
> The property 'kotlin.mpp.enableGranularSourceSetsMetadata=true' has no effect in this and future Kotlin versions, as Hierarchical Structures support is now enabled by default. It is safe to remove the property.
> feat: add binary-compatibility-validator plugin

- aws-crt-kotlin/build.gradle.kts
- gradle.properties
The migrated [publish logic](https://github.com/awslabs/aws-kotlin-repo-tools/blob/main/build-plugins/src/main/kotlin/aws/sdk/kotlin/gradle/dsl/Publish.kt#L105) in the shared build plugin expects `publishGroupName` or else it disables the nexus publishing tasks. The release stacks for `aws-sdk-kotlin` and `smithy-kotlin` explicitly set this property, rather than update the stack I've just set it directly since we only have one publishing group. 
> fix: fix publishing properties

- elasticurl/src/commonMain/kotlin/Application.kt
Related to https://github.com/awslabs/aws-sdk-kotlin/issues/860
This change removes some now-unnecessary opt-ins for experimental annotations. No functional change.
> chore: remove unused experimental annotations

- aws-crt-kotlin/api/android/aws-crt-kotlin.api
- aws-crt-kotlin/api/jvm/aws-crt-kotlin.api
- aws-crt-kotlin/build.gradle.kts
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/CRTNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/PlatformNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/CachedCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/DefaultChainCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/EcsCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/ProfileCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/StaticCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/StsAssumeRoleCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/StsWebIdentityCredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/credentials/X509CredentialsProviderNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/signing/AwsSignerNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/ClientBootstrapNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/EventLoopGroupNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/HostResolverNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/MutableBufferNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/TlsContextNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/UriNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/util/DigestNative.kt
- aws-crt-kotlin/native/test/aws/sdk/kotlin/crt/UtilsNative.kt
- build.gradle.kts
- builder.json
Adds a base implementation for `native` target
> fix: add base implementation for `native` target

- build.gradle.kts
- gradle.properties
Bumps the heap memory to 2G and metaspace memory to 1G to resolve OOM errors during builds.
> misc: bump allocated heap and metaspace memory

- aws-crt-kotlin/api/android/aws-crt-kotlin.api
- aws-crt-kotlin/api/jvm/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/CRT.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/CRT.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/CRTNative.kt
*Issue #, if available:* (none)
Adds a binding for determining if a CRT HTTP exception is retryable according to the [logic already coded in **aws-crt-java**](https://github.com/awslabs/aws-crt-java/blob/1cb7add5fa641c62f8445c9690cba25c4e272aa5/src/native/http_request_response.c#L713-L740).
**Companion PR**: https://github.com/awslabs/smithy-kotlin/pull/990
> feat: add support for determining HTTP exception retryability

- .changes/c2af8534-4505-415d-bafa-ab035e261c08.json
- aws-crt-kotlin/common/test/aws/sdk/kotlin/crt/http/HttpClientConnectionTest.kt
- gradle.properties
Bump dependencies to their latest available versions
> misc: bump dependency versions

- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
Upgrades the build to move away from source dependencies and use published version from our own "private" maven repository.
> chore: upgrade to published version

- .changes/cfc58da7-d2c6-47d7-a40e-72893b49bca7.json
- aws-crt-kotlin/api/android/aws-crt-kotlin.api
- aws-crt-kotlin/api/jvm/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/http/HttpStreamMetrics.kt
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/http/HttpStreamResponseHandler.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/http/HttpRequestUtil.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/http/HttpStreamMetricsJVM.kt
- build.gradle.kts
- gradle/libs.versions.toml
**Issue #, if available**: https://github.com/awslabs/smithy-kotlin/issues/893
**Description of changes**: This change consumes upstream changes in https://github.com/awslabs/aws-crt-java/pull/738 which provide a new callback for receiving metrics from HTTP streams
**Companion PRs**: https://github.com/awslabs/aws-crt-java/pull/738, https://github.com/awslabs/smithy-kotlin/pull/1017
> feat: enable access to metrics for HTTP streams

- .changes/11a891eb-b51f-4508-9010-f17d35ce96a3.json
- aws-crt-kotlin/api/android/aws-crt-kotlin.api
- aws-crt-kotlin/api/jvm/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManager.kt
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/http/HttpManagerMetrics.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerJVM.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerNative.kt
https://github.com/awslabs/smithy-kotlin/issues/893
This change makes HTTP manager metrics available in the Kotlin API.
**Companion PR**: https://github.com/awslabs/smithy-kotlin/pull/1017
> feat: surface HTTP connection manager metrics

- .brazil.json
**refactor**: Add a new `.brazil.json` file with the transform logic for just `aws-sdk-kotlin`. **NOTE**: This will not take effect until we release a new version of `kat` and update the release pipeline to use it. Until then the "global" transform config from repo tools is still the one being used. I tested this locally already and diffed the transform output using the one from repo tools and this new localized copy
> chore: relocate brazil transform

- .changes/87608337-174a-46aa-add3-8ec1370c737c.json
- aws-crt-kotlin/api/android/aws-crt-kotlin.api
- aws-crt-kotlin/api/jvm/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/auth/signing/AwsSigningConfig.kt
Add some features related to implementation of S3 Express support:
- Add `SIGV4_S3EXPRESS` signing algorithm
- Add `toBuilder` utility function to `AwsSigningConfig`
> feat: add `toBuilder` and S3 Express signing algorithm

- CMakeLists.txt
- aws-crt-kotlin/build.gradle.kts
- aws-crt-kotlin/native/interop/crt.def
- docker-images/linux-arm64/Dockerfile
- docker-images/linux-x64/Dockerfile
K/N toolchain uses glibc version 2.19 whereas the version we were using was 2.31 or thereabouts which are not compatible. This is fixed by leveraging the manlinux image. 
Additionally on arm64 CRT was adding the `-moutline-atomics` compiler flag which is added by [AwsCFlags ](https://github.com/awslabs/aws-c-common/blob/main/cmake/AwsCFlags.cmake#L124-L144). It would seem K/N version of gcc toolchain is too old:
```
Exception in thread "main" java.lang.Error: error: unknown argument: '-moutline-atomics'
at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:275)
at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1246)
at …
```
> fix: use same toolchain on arm that k/n does

- CMakeLists.txt
- aws-crt-kotlin/native/interop/crt.def
- docker-images/linux-x64/Dockerfile
- docker-images/linux-x64/Toolchain.cmake
This PR does a few things:
1. https://github.com/awslabs/aws-crt-kotlin/pull/98 removed the `linkerOpts` from crt.def. This is correct because included `staticLibraries` are automatically linked. The issue is that the order those libraries are linked doesn't seem controllable and it started causing linker issues (even without the changes in that branch). This PR extends the cmake build to bundle all of the individual static libraries into a single static lib `libaws-crt-kotlin.a` for consumption by the kotlin native toolchain.
2. https://github.com/awslabs/aws-crt-kotlin/pull/95 updated the `linuxArm64` target to build in a docker image that uses the same toolchain that K/N does. This PR does the same thing for the `linuxX64` target.
By …
> fix static libraries

- aws-crt-kotlin/build.gradle.kts
Fixes iOS simulator TLS negotiation errors by disabling `standalone` mode in simulator tests. The root cause is not known, but disabling `standalone` fixes the TLS issues. https://youtrack.jetbrains.com/issue/KT-38317.
Disabling standalone means we need to manage the simulator ourselves. This is done by registering new Gradle tasks to boot and shutdown the simulator when needed.
> fix: iOS simulator TLS negotiation errors

- .changes/1803e06b-e4dc-4566-bb54-e05ff90eb5d3.json
- .gitignore
- build.gradle.kts
- gradle/libs.versions.toml
Upgrade to the latest version of aws-crt-java which [recently added support for GraalVM](https://github.com/awslabs/aws-crt-java/pull/791)
> misc: upgrade to latest version of aws-crt-java

- .brazil.json
- .changes/bc0b11a8-48ce-4bc0-8b3f-4ee858477647.json
- gradle/libs.versions.toml
> misc: upgrade to kotlinx.coroutines 1.9.0

- .changes/49b860c3-3fce-40fa-acf7-e97650f49016.json
- .changes/963ddb76-2622-44d7-bb41-3439a5f033a5.json
- aws-crt-kotlin/jvm/test/aws/sdk/kotlin/crt/auth/credentials/ProfileCredentialsProviderTest.kt
- gradle/libs.versions.toml
> misc: upgrade aws-crt-java version

- CHANGELOG.md
> docs: rename `awslabs/smithy-kotlin` to `smithy-lang/smithy-kotlin`

- .github/workflows/artifact-size-metrics.yml
- .github/workflows/changelog-verification.yml
- .github/workflows/dependabot.yml
- .github/workflows/kat-transform.yml
(none)
Add the standard **main** workflows to ***-main** branches.
> chore: add *-main to branch workflows

- .brazil.json
- .changes/337cca7e-6a38-4601-b5d2-9f8d12dd60f7.json
- aws-crt-kotlin/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
> misc: Upgrade to Kotlin 2.1.0

- .changes/a070184a-04e1-46b7-bbb7-73d7cf95b495.json
- gradle/libs.versions.toml
(none)
Upgrade to the latest CRT release to pick up [changes to skip signing `Transfer-Encoding` header](https://github.com/awslabs/aws-c-auth/pull/261).
> fix: upgrade CRT version to pick up header signing changes

- .github/workflows/changelog-verification.yml
- .github/workflows/ci.yaml
N/A
`actions/cache@v2` is deprecated and causing our CI to fail. See:
https://github.com/awslabs/aws-crt-kotlin/actions/runs/13793400399/job/38578895984?pr=133
This PR also version bumps `actions/checkout` to `v4`, which was not causing issues
> misc: `actions/checkout` & `actions/cache` version bump

- .github/workflows/api-compat-verification.yml
- gradle.properties
> misc: add api-compat-verification workflow

- gradle/libs.versions.toml
(none)
Upgrade **aws-kotlin-repo-tools** to **0.4.22** to pick up [fix for compiler warning](https://github.com/awslabs/aws-kotlin-repo-tools/pull/82).
> chore: upgrade aws-kotlin-repo-tools

- .changes/3d6fffae-2ce4-478f-b410-fce0afe16588.json
- aws-crt-kotlin/api/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/io/TlsCipherPreference.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/io/TlsContextJVM.kt
- gradle/libs.versions.toml
(none)
Updates the list of supported cipher preferences to match [what CRT supports](https://github.com/awslabs/aws-c-io/blob/8286c781b95b426ca2f0783b6c1fe49ff519c4e7/include/aws/io/tls_channel_handler.h#L30-L47), specifically:
* Adds support for `PQ_TLSV1_2_2024_10` and `PQ_DEFAULT`
* Deprecates `PQ_TLS_V1_0_2021_05`
* Updates **aws-crt-java** version to [**v0.38.1**](https://github.com/awslabs/aws-crt-java/releases/tag/v0.38.1)
> fix: update supported TLS cipher preferences

- aws-crt-kotlin/api/aws-crt-kotlin.api
- build.gradle.kts
(none)
Removes unnecessary `-jvm-default=no-compatibility` flag added in #160.
> fix: remove unnecessary `-jvm-default=no-compatibility` compiler flag

- aws-crt-kotlin/api/aws-crt-kotlin.api
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/io/ClientBootstrap.kt
- aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/io/HostResolver.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/io/ClientBootstrapJVM.kt
- aws-crt-kotlin/jvm/src/aws/sdk/kotlin/crt/io/HostResolverJVM.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/ClientBootstrapNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/EventLoopGroupNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/HostResolverNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/TlsContextNative.kt
#96 
This change adds child resource tracking/management for HTTP-related Kotlin/Native CRT resources.
> fix: correctly close HTTP-related CRT resources in native sourceset

- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/auth/signing/AwsSignerNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/http/HttpClientConnectionNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/http/HttpStreamNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/io/HostResolverNative.kt
- aws-crt-kotlin/native/src/aws/sdk/kotlin/crt/util/DigestNative.kt
(none)
This change fixes a few more instances of flaky native reference handling:
* Add `WithCrt` to more classes which require initializing the CRT
* Track stream, connection, and connection manager closure with a boolean flag so that underlying CRT APIs are called at most once
* Store the `HttpStreamNative` reference in connection callbacks instead of recreating the stream inside every callback, which would make it difficult to properly track closure
> chore: fix more instances of flaky native reference handling

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/artifact-size-metrics.yml
- .github/workflows/changelog-verification.yml
- .github/workflows/kat-transform.yml
- .github/workflows/merge-main.yml
- CODEOWNERS
- CONTRIBUTING.md
Migrate repository references from awslabs to aws organization following GitHub repository transfer.
> chore: migrate repo from awslabs to aws

- aws-crt-kotlin/build.gradle.kts
- gradle/libs.versions.toml
> misc: disable cinterop tasks if not buildable
